#!/bin/sh

#Credit: Aixxe @ aixxe.net
if grep -q libMonoLoader.so /proc/$(pidof rust)/maps; then
sudo gdb -n -q -batch \
    -ex "attach $(pidof rust)" \
    -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
    -ex "set \$dlclose = (int(*)(void*)) dlclose" \
    -ex "set \$library = \$dlopen(\"$(pwd)/libMonoLoader.so\", 6)" \
    -ex "call \$dlclose(\$library)" \
    -ex "call \$dlclose(\$library)" \
    -ex "detach" \
    -ex "quit"
fi